name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.24.x] # when updating versions, update it below too.
    runs-on: ${{ matrix.os }}
    name: Test
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test
      continue-on-error: ${{ matrix.os != 'ubuntu-latest' || matrix.go != '1.24.x' }}
      run: |
        go test -race -covermode atomic -coverprofile=profile.cov ./...

    - name: Code coverage
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.24.x' }}
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
